name: 'Update Task Definition Environment'
description: 'Action to update AWS task-definition environment variables'
author: 'INNOSOL'
inputs:
  variables:
    required: true
    description: 'JSON-stringified object of environment variables'
  task-definition:
    required: true
    description: 'The task definition JSON file'
    default: 'task-definition.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
